# 服务器端口
server:
  port: 8082

#配置远程mysql数据库
spring:
  datasource:
    url: jdbc:mysql://39.108.251.216:3306/YangJiangBo?useSSL=false&amp;serverTimezone=Hongkong&amp;characterEncoding=utf-8&amp;autoReconnect=true
    username: YangJiangBo
    password: YJB123456
    #url: jdbc:mysql://localhost:3306/bookshop?setUnicode=true&characterEncoding=utf8
    #username: root
    #password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
#配置mybatis依赖
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.sitech.cloudide.bean

#### redis #### 依赖
spring.redis: 
#Redis数据库索引（默认为0）
  database: 0
  host: 172.18.231.108
#Redis服务器连接端口
  port: 9738
#Redis服务器连接密码（默认为空）
  password: Cn@aDm443
#连接池最大连接数（使用负值表示没有限制）默认8
  lettuce.pool: 
    max-active: 8
#连接池最大阻塞等待时间（使用负值表示没有限制）默认-1
    max-wait: -1
#连接池中的最大空闲连接默认8
    max-idle: 8
#连接池中的最小空闲连接默认e
    min-idle: 0
# 连接超时时间（毫秒）
    timeout: 0
#spring-session 使用
  session.store-type: none
