server:
  port: 8082

#mysql
spring:
  datasource:
    url: jdbc:mysql://47.96.143.152:3306/YJB?useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    username: root
    password: 'Yjw970827'
    #url: jdbc:mysql://localhost:3306/bookshop?setUnicode=true&characterEncoding=utf8
    #username: root
    #password: root
    driver-class-name: com.mysql.jdbc.Driver
    
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.sitech.cloudide.bean

#### redis #### 依赖
spring.redis: 
  database: 0
  host: 172.18.231.108
  port: 9738
  password: Cn@aDm443
#连接池最大连接数（使用负值表示没有限制）默认8
  lettuce.pool: 
    max-active: 8
#连接池最大阻塞等待时间（使用负值表示没有限制）默认-1
    max-wait: -1
#连接池中的最大空闲连接默认8
    max-idle: 8
#连接池中的最小空闲连接默认e
    min-idle: 0
# 连接超时时间（毫秒）
    timeout: 1000
#spring-session 使用
  session.store-type: none
