# 服务器端口
server:
  port: 8082

#配置远程mysql数据库
spring:
  datasource:
    url: jdbc:mysql://47.96.143.152:3306/YJB?useSSL=false&amp;serverTimezone=Hongkong&amp;characterEncoding=utf-8&amp;autoReconnect=true
    username: root
    password: Yjw970827
    driver-class-name: com.mysql.jdbc.Driver
  quartz:
    #相关属性配置
    #数据持久化到数据库方式：jdbc    任务调度信息默认是memory
    job-store-type: jdbc
    # 启动后初始化数据库的模式，3种模式（ALWAYS、EMBEDDED、NEVER）
    initialize-schema: embedded     
    properties:
      org:
        quartz:
          scheduler:
            #ID设置为自动获取 每一个必须不同 （所有调度器实例中是唯一的）
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore: 
            #数据保存方式为持久化
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            #表的前缀
            tablePrefix: QRTZ_
            # 是否加入集群
            isClustered: true
            #调度实例失效的检查时间间隔
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            #ThreadPool 实现的类名
            class: org.quartz.simpl.SimpleThreadPool
            #线程数量
            threadCount: 10
            #线程优先级 min:1- max:10
            threadPriority: 5
            #自创建父线程
            threadsInheritContextClassLoaderOfInitializingThread: true
  # thymeleaf 配置
  thymeleaf:
    #模式
    mode: HTML
    #编码格式
    encoding: UTF-8
    #视图解析器 资源目录前缀
    prefix: classpath:/templates/
    #资源后缀
    suffix: .html
    #不使用缓存
    cache: false
    
#配置mybatis依赖
mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: com.sitech.cloudide.bean

#### redis #### 依赖
redis: 
#Redis数据库索引（默认为0）
    database: 0
    host: 172.18.231.108
#Redis服务器连接端口
    port: 9738
#Redis服务器连接密码（默认为空）
    password: Cn@aDm443
#连接池最大连接数（使用负值表示没有限制）默认8
    lettuce.pool: 
    max-active: 8
#连接池最大阻塞等待时间（使用负值表示没有限制）默认-1
    max-wait: -1
#连接池中的最大空闲连接默认8
    max-idle: 8
#连接池中的最小空闲连接默认e
    min-idle: 0
# 连接超时时间（毫秒）
    timeout: 0
#spring-session 使用
    session.store-type: none



  